FROM maven:3.8.6-openjdk-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/ms-retoindra-customer-backend-0.0.1-SNAPSHOT.jar /app/ms-retoindra-customer-backend-0.0.1-SNAPSHOT.jar
EXPOSE 8001
ENTRYPOINT ["java", "-jar", "/app/ms-retoindra-customer-backend-0.0.1-SNAPSHOT.jar"]
